// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiANTjt54g6Xuo9I_tH3hDXIvQjSLhGGw',
    appId: '1:700414414917:web:b738f15a5b35684083532c',
    messagingSenderId: '700414414917',
    projectId: 'fir-demoflutter-d0918',
    authDomain: 'fir-demoflutter-d0918.firebaseapp.com',
    storageBucket: 'fir-demoflutter-d0918.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_4p1IUazPPOWskLdSBxWrL3wGFgV2BB8',
    appId: '1:700414414917:android:9d3201da563e783d83532c',
    messagingSenderId: '700414414917',
    projectId: 'fir-demoflutter-d0918',
    storageBucket: 'fir-demoflutter-d0918.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARmz_mT_GHbEQXZ4e_WfgV2MU46Fmy4aw',
    appId: '1:700414414917:ios:3ffb78bf85251a5983532c',
    messagingSenderId: '700414414917',
    projectId: 'fir-demoflutter-d0918',
    storageBucket: 'fir-demoflutter-d0918.appspot.com',
    iosClientId:
        '700414414917-fivpop7ol584cjg6h07jkfrbeg7o08c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARmz_mT_GHbEQXZ4e_WfgV2MU46Fmy4aw',
    appId: '1:700414414917:ios:3ffb78bf85251a5983532c',
    messagingSenderId: '700414414917',
    projectId: 'fir-demoflutter-d0918',
    storageBucket: 'fir-demoflutter-d0918.appspot.com',
    iosClientId:
        '700414414917-fivpop7ol584cjg6h07jkfrbeg7o08c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbtest',
  );
}
