// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQf8M55TQPE8_JbQJYzNc1aiWw_ZxUIs0',
    appId: '1:226473072677:web:dd09c11cfd0e50d54e47cc',
    messagingSenderId: '226473072677',
    projectId: 'db-test-22ba8',
    authDomain: 'db-test-22ba8.firebaseapp.com',
    storageBucket: 'db-test-22ba8.appspot.com',
    measurementId: 'G-Y6QV1909BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXOG453PIopf47bZt9xkF04XgU_tkJ9dU',
    appId: '1:226473072677:android:a0174c008913868c4e47cc',
    messagingSenderId: '226473072677',
    projectId: 'db-test-22ba8',
    storageBucket: 'db-test-22ba8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqvlz6iLFXXbYXFaoJnCRvTnHMW8BEZbI',
    appId: '1:226473072677:ios:b2bfc6e6cfc24ae44e47cc',
    messagingSenderId: '226473072677',
    projectId: 'db-test-22ba8',
    storageBucket: 'db-test-22ba8.appspot.com',
    iosClientId: '226473072677-5im8vl8l7l0abl0ombeo12h19pbfec14.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqvlz6iLFXXbYXFaoJnCRvTnHMW8BEZbI',
    appId: '1:226473072677:ios:b2bfc6e6cfc24ae44e47cc',
    messagingSenderId: '226473072677',
    projectId: 'db-test-22ba8',
    storageBucket: 'db-test-22ba8.appspot.com',
    iosClientId: '226473072677-5im8vl8l7l0abl0ombeo12h19pbfec14.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbtest',
  );
}
